# Generated by Django 3.2 on 2021-04-17 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golfer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='golfer',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tourngolfer',
            options={'managed': False, 'verbose_name': 'Tournament Golfer', 'verbose_name_plural': 'Tournament Golfers'},
        ),
    ]
