# Generated by Django 3.2 on 2021-04-17 11:33

from django.db import migrations
import csv


class Migration(migrations.Migration):

    def add_city_data(apps, schema_editor):
        with open('golfersInput.csv', newline='') as csvfile:
            csvreader = csv.reader(csvfile, delimiter=',')
            golfers = list(csvreader)
            for golfer in golfers:
                # strip whitespace of each golfer element
                str(golfer[0]).strip()
                str(golfer[1]).strip()
                str(golfer[2]).strip()
            csvfile.close()

        Golfer = apps.get_model('golfer', 'Golfer')
        for name, bdate, city in golfers:
            golfer = Golfer.objects.get(golfer_name=name)
            golfer.golfer_city = city
            golfer.save()

    def remove_city_data(apps, scheme_editor):
        Golfer = apps.get_model('golfer', 'Golfer')
        Golfer.objects.update(golfer_city='unknown')

    dependencies = [
        ('golfer', '0003_add_golfer_city'),
    ]

    operations = [
        migrations.RunPython(add_city_data, reverse_code=remove_city_data)
    ]
