# Generated by Django 3.1.7 on 2021-03-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('round_id', models.IntegerField(primary_key=True, serialize=False)),
                ('round_day', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Round',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tourn_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tourn_name', models.TextField(blank=True, null=True)),
                ('tourn_start_date', models.DateField(blank=True, null=True)),
                ('tourn_num_rounds', models.IntegerField(blank=True, null=True)),
                ('tourn_num_golfers', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Tournament',
                'managed': False,
            },
        ),
    ]
