# Generated by Django 3.1.7 on 2021-03-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GolfCourse',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.TextField()),
                ('course_total_par', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Golf Course',
                'verbose_name_plural': 'Golf Courses',
                'db_table': 'GolfCourse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('hole_id', models.IntegerField(primary_key=True, serialize=False)),
                ('hole_number', models.IntegerField()),
                ('hole_par', models.IntegerField()),
            ],
            options={
                'db_table': 'Hole',
                'managed': False,
            },
        ),
    ]
